### PR TITLE
Convert synchronous client call to asynchronous for CallStacking.com

### PR DESCRIPTION
**Pull request by deyemiobaa**
Hi @aantix. In this PR, I used the "async-http" gem to convert the trace call to an async call.

### CODE REVIEW

**Comment by aantix** [comment]
Super fast! 🙏  

I assigned the bounty to you.

I'll take a look over the weekend and provide feedback.

**Comment by deyemiobaa** [comment]
Thank you!

**Comment by aantix** [comment]
Was testing out your branch.

The async dependency needs to be listed in the .gemspec.  

Otherwise, the require will fail within the context of the engine.  The `require 'async'` is currently failing in client/trace.rb.

Can you both test the engine with a current Rails app and write some tests for the Client::Trace class?

**Comment by deyemiobaa** [comment]
I wrote a test to test the post request in the trace class.

Regarding testing the engine with a current Rails app. I'm not 100% sure how to go about that. Could point me in the right direction please.
here's what I got from personal research:

- run rake build to build a .gem file
- add the gem to the app by specifying the path to the .gem (I'm guessing to use the dummy app for this / replace with a working app)
- then bundle install

Is this a right approach?

**Comment by aantix** [comment]
You'll want to do a basic smoke test ( https://en.wikipedia.org/wiki/Smoke_testing_(software) ).  

Since these changes are part of a Rails engine, we need to test it within the context of another Rails app.  
The engine is a dependency listed in the Gemfile of a Rails app. 

You'll want to follow the setup instruction outlined here ( https://callstacking.com/#setup ).  

But instead of referencing the published gem, you'll want to point the Gemfile at your local version with the changes.

Instead of :

```
gem 'callstacking-rails', '0.1.18'
```

You'll want to do:
```
gem 'callstacking-rails', path: "/local/path/to/callstacking-rails"
```

Then follow the rest of the instructions.

**Comment by aantix** [comment]
Let me know if you have any issues.  We can jump on a Zoom call and pair on it.

**Comment by deyemiobaa** [comment]
Hi, sorry for the late response. 

I have placed the gem in another app using the local path and it installs successfully. However, when I try to register using `bundle exec callstacking-rails register`. It throws an error "

```bash
$ bundle exec callstacking-rails register
bundler: failed to load command: callstacking-rails (/home/deyemiobaa/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/bin/callstacking-rails)
/home/deyemiobaa/projects/callstacking-rails/exe/callstacking-rails:20:in ``': No such file or directory - open (Errno::ENOENT)
```
The error points to this file on line 20
image

**Comment by deyemiobaa** [comment]
I'm open to join a zoom call, what day/time would work for you

**Comment by aantix** [comment]
Good find.  I was doing an `open <URL>`, but that's only valid on OSX.  It throws an exception on Linux.

Pull down my changes and you should be able to proceed.

**Comment by aantix** [comment]
@deyemiobaa How about tomorrow night?  Sunday, March 12th, 10 pm CST?

Email me at jim.jones1@gmail.com

**Comment by deyemiobaa** [comment]
@aantix That might be a bit tough for me to catch up with. That time is equivalent to 5am my time here. 

And I would really need to join a call with you. The recent changes you made seems to break a lot of things on my branch. Mostly caused by the Faraday gem, and I'm not sure if this is because of the Linux OS.

I can meet between 9am - 12pm CST, 2pm - 5pm CST. Do any of those work for you?

**Comment by aantix** [comment]
Perfect.  How about Monday, 10am, CST?

Email me, and I can send you a Zoom link.

**Pull request closed without merging**
